"""unique display name

Revision ID: 3ea476d22916
Revises: ab50114ee862
Create Date: 2026-07-20 18:45:26.599305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea476d22916'
down_revision: Union[str, Sequence[str], None] = 'ab50114ee862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_state',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_display_name'), ['display_name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_display_name'), type_='unique')

    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_state',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'ready'"),
               existing_nullable=False)

    # ### end Alembic commands ###
