"""unique display name

Revision ID: 3ea476d22916
Revises: ab50114ee862
Create Date: 2026-07-20 18:45:26.599305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea476d22916'
down_revision: Union[str, Sequence[str], None] = 'ab50114ee862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _deduplicate_display_names() -> None:
    """Makes existing display names unique before the constraint is added.

    A database that predates this rule can hold duplicates, case-equivalent
    names ("Euan" / "euan"), and blanks — all of which the constraint rejects.
    Adding it without cleaning first fails the whole upgrade with
    `UNIQUE constraint failed`, which is a bad way to find out during a deploy.

    The rules:
      * an empty display name becomes the username — that is what registration
        would have set, and it is unique already;
      * duplicates keep the oldest holder's name and everyone else gets their
        username, falling back to a numbered suffix if that is somehow taken.

    Nobody loses an account and nobody has to intervene by hand.
    """
    connection = op.get_bind()
    rows = connection.execute(
        sa.text(
            "SELECT id, username, display_name FROM users "
            "ORDER BY created_at, id"
        )
    ).fetchall()

    seen: set[str] = set()
    for user_id, username, display_name in rows:
        current = (display_name or "").strip()
        key = current.lower()

        if current and key not in seen:
            seen.add(key)
            continue

        # Blank, or a name somebody older already holds.
        candidate = username
        suffix = 1
        while candidate.lower() in seen:
            suffix += 1
            candidate = f"{username}{suffix}"

        seen.add(candidate.lower())
        connection.execute(
            sa.text("UPDATE users SET display_name = :name WHERE id = :id"),
            {"name": candidate, "id": user_id},
        )


def upgrade() -> None:
    """Upgrade schema."""
    # Runs before the constraint: the constraint is what would otherwise fail.
    _deduplicate_display_names()

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_state',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_display_name'), ['display_name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_display_name'), type_='unique')

    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.alter_column('thumbnail_state',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'ready'"),
               existing_nullable=False)

    # ### end Alembic commands ###
