"""media files

Revision ID: 90050e90fafa
Revises: f536e1770c64
Create Date: 2026-07-20 16:58:12.478756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90050e90fafa'
down_revision: Union[str, Sequence[str], None] = 'f536e1770c64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('visibility', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_files_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_visibility'), ['visibility'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_files_visibility'))
        batch_op.drop_index(batch_op.f('ix_media_files_sha256'))
        batch_op.drop_index(batch_op.f('ix_media_files_owner_id'))
        batch_op.drop_index(batch_op.f('ix_media_files_kind'))
        batch_op.drop_index(batch_op.f('ix_media_files_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_media_files_created_at'))

    op.drop_table('media_files')
    # ### end Alembic commands ###
