"""thumbnail state

Revision ID: ab50114ee862
Revises: ec30615628e5
Create Date: 2026-07-20 18:44:31.279757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab50114ee862'
down_revision: Union[str, Sequence[str], None] = 'ec30615628e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'thumbnail_state', sa.String(length=16),
                nullable=False, server_default='ready',
            )
        )
        batch_op.alter_column('has_thumbnail',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_media_files_thumbnail_state'), ['thumbnail_state'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_files_thumbnail_state'))
        batch_op.alter_column('has_thumbnail',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('0'),
               existing_nullable=False)
        batch_op.drop_column('thumbnail_state')

    # ### end Alembic commands ###
