"""places and footprint visits

Revision ID: af59e0f6e597
Revises: 3ea476d22916
Create Date: 2026-07-23 23:08:36.104586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af59e0f6e597'
down_revision: Union[str, Sequence[str], None] = '3ea476d22916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_places_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_places')),
    sa.UniqueConstraint('owner_id', 'city', 'country_code', name='uq_owner_city_country')
    )
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_places_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_places_owner_id'), ['owner_id'], unique=False)

    op.create_table('footprint_visits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.String(length=32), nullable=False),
    sa.Column('place_id', sa.String(length=32), nullable=False),
    sa.Column('visited_on', sa.DateTime(), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_footprint_visits_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('fk_footprint_visits_place_id_places'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_footprint_visits'))
    )
    with op.batch_alter_table('footprint_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_footprint_visits_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_footprint_visits_place_id'), ['place_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_footprint_visits_source_ref'), ['source_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_footprint_visits_visited_on'), ['visited_on'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('footprint_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_footprint_visits_visited_on'))
        batch_op.drop_index(batch_op.f('ix_footprint_visits_source_ref'))
        batch_op.drop_index(batch_op.f('ix_footprint_visits_place_id'))
        batch_op.drop_index(batch_op.f('ix_footprint_visits_owner_id'))

    op.drop_table('footprint_visits')
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_places_owner_id'))
        batch_op.drop_index(batch_op.f('ix_places_country_code'))
        batch_op.drop_index(batch_op.f('ix_places_city'))

    op.drop_table('places')
    # ### end Alembic commands ###
