"""media association and thumbnails

Revision ID: ec30615628e5
Revises: 90050e90fafa
Create Date: 2026-07-20 17:32:18.665091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec30615628e5'
down_revision: Union[str, Sequence[str], None] = '90050e90fafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_id', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('orphaned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column('has_thumbnail', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_media_files_content_id'), ['content_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_files_orphaned_at'), ['orphaned_at'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_media_files_content_id_contents'), 'contents', ['content_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_files', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_media_files_content_id_contents'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_media_files_orphaned_at'))
        batch_op.drop_index(batch_op.f('ix_media_files_content_id'))
        batch_op.drop_column('has_thumbnail')
        batch_op.drop_column('orphaned_at')
        batch_op.drop_column('content_id')

    # ### end Alembic commands ###
